### PR TITLE
Add Landing Page Navbar

### PR DESCRIPTION
**Pull request by SujeethJinesh**
Added Landing Page Navbar. Still need to add React Router logic for switching pages and stuff as the pages become available.

Mockup:
landingPageNavbar

Implementation:
Screen Shot 2019-03-15 at 2 46 12 AM

### CODE REVIEW

**Comment by SujeethJinesh** [comment]
Resolved Merge conflicts

Screen Shot 2019-03-15 at 11 24 09 AM

**Comment by mliu356** [comment]
idk why the Parent sign in button is just dying :(

Screen Shot 2019-03-15 at 11 35 04 AM

**Comment by SujeethJinesh** [comment]
> idk why the Parent sign in button is just dying :(
> 
> Screen Shot 2019-03-15 at 11 35 04 AM

Cri, i'll take a look at it rn. Styling is a pain 😭

**Comment by SujeethJinesh** [comment]
Resolved Merge Conflicts
Screen Shot 2019-03-15 at 12 30 12 PM

**Pull request merged**
