### PR TITLE
Infographic

### LINKED ISSUE #110: Landing page infographic
Uploaded as an image

image

### PR DESCRIPTION
**Pull request by Stephanie-A**
closes #110

### CODE REVIEW

**Comment by SujeethJinesh** [comment]
Resolve merge conflicts, and rebase on master because these changes were connected to your index.js PR. Hopefully this will clean up some of the differences between them!

**Comment by Stephanie-A** [comment]
> This change was fine, I meant reverting `package-lock.json` not `package.json`. Heroku will build our own package-lock.json there, so we don't actually need it here. I'll make a PR later to just ignore any package-lock.json files

How I revert it to master?

**Comment by SujeethJinesh** [comment]
> > This change was fine, I meant reverting `package-lock.json` not `package.json`. Heroku will build our own package-lock.json there, so we don't actually need it here. I'll make a PR later to just ignore any package-lock.json files
> 
> How I revert it to master?

`git checkout origin/master -- package-lock.json` and do that for client/package-lock.json and server as well

**Comment by Stephanie-A** [comment]
> > > This change was fine, I meant reverting `package-lock.json` not `package.json`. Heroku will build our own package-lock.json there, so we don't actually need it here. I'll make a PR later to just ignore any package-lock.json files
> > 
> > 
> > How I revert it to master?
> 
> `git checkout origin/master -- package-lock.json` and do that for client/package-lock.json and server as well

It says that there's no client/server package-lock.json

**Comment by SujeethJinesh** [comment]
> > > > This change was fine, I meant reverting `package-lock.json` not `package.json`. Heroku will build our own package-lock.json there, so we don't actually need it here. I'll make a PR later to just ignore any package-lock.json files
> > > 
> > > 
> > > How I revert it to master?
> > 
> > 
> > `git checkout origin/master -- package-lock.json` and do that for client/package-lock.json and server as well
> 
> It says that there's no client/server package-lock.json

Oh gotcha, that means that it's not on master. You can just delete those files. I'll make a PR right now to remove package-locks in the gitignore

**Comment by Stephanie-A** [comment]
> > > > > This change was fine, I meant reverting `package-lock.json` not `package.json`. Heroku will build our own package-lock.json there, so we don't actually need it here. I'll make a PR later to just ignore any package-lock.json files
> > > > 
> > > > 
> > > > How I revert it to master?
> > > 
> > > 
> > > `git checkout origin/master -- package-lock.json` and do that for client/package-lock.json and server as well
> > 
> > 
> > It says that there's no client/server package-lock.json
> 
> Oh gotcha, that means that it's not on master. You can just delete those files. I'll make a PR right now to remove package-locks in the gitignore

Any idea why the snyk checks are failing and how to fix them?

**Pull request merged**
