### PR TITLE
About us card

### PR DESCRIPTION
**Pull request by SujeethJinesh**
Added AboutUs card. I put the image in as a placeholder, but the background is gray.

Mockup:
aboutUs

Implementation:
Screen Shot 2019-03-14 at 1 32 51 PM

### CODE REVIEW

**Comment by mliu356** [comment]
Orientation within About Us card turns vertical again? (Did i mess something up?)

Screen Shot 2019-03-15 at 11 41 47 AM

**Comment by SujeethJinesh** [comment]
Resolved Merge Conflicts

Screen Shot 2019-03-15 at 12 25 32 PM

**Comment by SujeethJinesh** [comment]
Resolved Merge Conflicts

**Comment by SujeethJinesh** [comment]
Resolved Merge Conflicts
Screen Shot 2019-03-15 at 12 25 32 PM

**Pull request merged**
